Feature/edit delete user
openobservatoryteam/open-observatory pull request #68
Opened 2023-04-19 14:42 UTC by romain-hebert

2023-04-20 19:01 UTC, kevinbioj requested changes

2023-04-20 19:01 UTC, kevinbioj commented on src/main/java/fr/openobservatory/backend/controllers/UserController.java
> +  @PatchMapping("{username}/delete")
La route adéquate serait plutôt `DELETE /{username}`

2023-04-20 19:01 UTC, kevinbioj commented on src/main/java/fr/openobservatory/backend/controllers/UserController.java
> +  public ResponseEntity<Void> deleteUser(@PathVariable String username) {
Par soucis de cohérence, j'aurais appelé la méthode simplement `delete`.

2023-04-20 19:01 UTC, kevinbioj commented on src/main/java/fr/openobservatory/backend/services/UserService.java
> +  public void adminDeleteUser(String username) {
Pareil que pour le contrôleur

2023-04-20 19:01 UTC, kevinbioj commented on src/main/java/fr/openobservatory/backend/services/UserService.java
> +    if (username == null) throw new InvalidUsernameException();
Si `username` vaut null, il ne trouvera de toute façon rien (et lèvera l'UnknownUserException), en soit c'est pas vraiment utile de checker en amont.

2023-04-21 10:19 UTC, romain-hebert commented on src/main/java/fr/openobservatory/backend/services/UserService.java
> +    if (username == null) throw new InvalidUsernameException();
Même si dans le DAL c’est marqué de renvoyer BAD_REQUEST en cas de username invalid ?

2023-04-21 18:10 UTC, kevinbioj commented on src/main/java/fr/openobservatory/backend/services/UserService.java
> +    if (username == null) throw new InvalidUsernameException();
Avec le recul c'est un peu superflu dans le sens où ça fait du code en + à tester qui ne change de toute façon rien
Et aussi parce c'est fait nul part ailleurs (à part l'inscription mais c'est normal)

2023-05-03 08:54 UTC, merged